### ISSUE TITLE
template parse error

### ISSUE THREAD

**Issue by ghost** [gbrits/ionic-calendar#1]
I am getting this error I am using latest version 

Error: Template parse errors:
Can't bind to 'color' since it isn't a known property of 'ion-calendar-week'.
1. If 'ion-calendar-week' is an Angular component and it has 'color' input, then verify that it is part of this module.
2. If 'ion-calendar-week' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("

      <ion-calendar-week
        [ERROR ->][color]="_d.color"
        [weekArray]="_d.weekdays"
        [weekStart]="_d.weekStart">
"): ng:///AppModule/CalendarModal.html@24:8
Can't bind to 'weekArray' since it isn't a known property of 'ion-calendar-week'.
1. If 'ion-calendar-week' is an Angular component and it has 'weekArray' input, then verify that it is part of this module.
2. If 'ion-calendar-week' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
      <ion-calendar-week
        [color]="_d.color"
        [ERROR ->][weekArray]="_d.weekdays"
        [weekStart]="_d.weekStart">
      </ion-calendar-week>
"): ng:///AppModule/CalendarModal.html@25:8
Can't bind to 'weekStart' since it isn't a known property of 'ion-calendar-week'.
1. If 'ion-calendar-week' is an Angular component and it has 'weekStart' input, then verify that it is part of this module.
2. If 'ion-calendar-week' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
        [color]="_d.color"
        [weekArray]="_d.weekdays"
        [ERROR ->][weekStart]="_d.weekStart">
      </ion-calendar-week>

"): ng:///AppModule/CalendarModal.html@26:8
'ion-calendar-week' is not a known element:
1. If 'ion-calendar-week' is an Angular component, then verify that it is part of this module.
2. If 'ion-calendar-week' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
      </ion-navbar>

      [ERROR ->]<ion-calendar-week
        [color]="_d.color"
        [weekArray]="_d.weekdays"
"): ng:///AppModule/CalendarModal.html@23:6
Can't bind to 'month' since it isn't a known property of 'ion-calendar-month'.
1. If 'ion-calendar-month' is an Angular component and it has 'month' input, then verify that it is part of this module.
2. If 'ion-calendar-month' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("text-center month-title">{{_monthFormat(month.original.date)}}</h4>
            <ion-calendar-month [ERROR ->][month]="month"
                                [pickMode]="_d.pickMode"
                            "): ng:///AppModule/CalendarModal.html@38:32
Can't bind to 'pickMode' since it isn't a known property of 'ion-calendar-month'.
1. If 'ion-calendar-month' is an Angular component and it has 'pickMode' input, then verify that it is part of this module.
2. If 'ion-calendar-month' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("iginal.date)}}</h4>
            <ion-calendar-month [month]="month"
                                [ERROR ->][pickMode]="_d.pickMode"
                                [isSaveHistory]="_d.isSaveHistory"
         "): ng:///AppModule/CalendarModal.html@39:32
Can't bind to 'isSaveHistory' since it isn't a known property of 'ion-calendar-month'.
1. If 'ion-calendar-month' is an Angular component and it has 'isSaveHistory' input, then verify that it is part of this module.
2. If 'ion-calendar-month' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("h]="month"
                                [pickMode]="_d.pickMode"
                                [ERROR ->][isSaveHistory]="_d.isSaveHistory"
                                [id]="_d.id"
                     "): ng:///AppModule/CalendarModal.html@40:32
Can't bind to 'color' since it isn't a known property of 'ion-calendar-month'.
1. If 'ion-calendar-month' is an Angular component and it has 'color' input, then verify that it is part of this module.
2. If 'ion-calendar-month' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("ry]="_d.isSaveHistory"
                                [id]="_d.id"
                                [ERROR ->][color]="_d.color"
                                (onChange)="onChange($event)"
                    "): ng:///AppModule/CalendarModal.html@42:32
'ion-calendar-month' is not a known element:
1. If 'ion-calendar-month' is an Angular component, then verify that it is part of this module.
2. If 'ion-calendar-month' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("         <h4 class="text-center month-title">{{_monthFormat(month.original.date)}}</h4>
            [ERROR ->]<ion-calendar-month [month]="month"
                                [pickMode]="_d.pickMode"
        "): ng:///AppModule/CalendarModal.html@38:12
    at syntaxError (file:///android_asset/www/build/vendor.js:118742:34)
    at TemplateParser.parse (file:///android_asset/www/build/vendor.js:142588:19)
    at JitCompiler._parseTemplate (file:///android_asset/www/build/vendor.js:151975:37)
    at JitCompiler._compileTemplate (file:///android_asset/www/build/vendor.js:151950:23)
    at file:///android_asset/www/build/vendor.js:151852:62
    at Set.forEach (<anonymous>)
    at JitCompiler._compileComponents (file:///android_asset/www/build/vendor.js:151852:19)
    at file:///android_asset/www/build/vendor.js:151722:19
    at Object.then (file:///android_asset/www/build/vendor.js:118731:77)
    at JitCompiler._compileModuleAndComponents (file:///android_asset/www/build/vendor.js:151721:26)

PROBLEMS
OUTPUT
DEBUG CONSOLE
TERMINAL
JAVA_HOME=C:\Program Files\Java\jdk

**Comment by gbrits** [comment]
Hi @Faisalali23, I'd have to see your markup - it appears you're using *color* and *month* properties? This is my current usage:

    <ion-calendar #calendar [events]="currentEvents" (onDaySelect)="onDaySelect($event)" (onMonthSelect)="onMonthSelect($event)"></ion-calendar>

No other available props / attributes.

**Comment by gbrits** [comment]
Usage issue, not code issue.

**Comment by anasappsaya** [comment]
Any solution I have the same problem exactly the same !
