### ISSUE TITLE
up on date selection, current date is still highlighted #11

### ISSUE THREAD

**Issue by praveens96** [gbrits/ionic-calendar#10]
i am trying to use this plugin for showing calendar in my app. it all working fine but up on date selection, current date is still selected which gives a wrong impression to the user.
![image](https://user-images.githubusercontent.com/8864727/43136292-e30a126c-8f65-11e8-9739-5ffe1e4a3f9b.png)
was anybody able to fix this?

**Comment by gbrits** [comment]
Hi there @praveens96 - thanks for using the package, this can be a simple fix just with some CSS, for example: 

`.select {
      box-shadow: none;
      color: #000;
      background: #f2f2f2;
      border-radius: 3px;
    }`

That would differentiate your today from your selected more accurately - perhaps in a future update I will adjust this by default.
