### ISSUE TITLE
Ionic 4 not working

### ISSUE THREAD

**Issue by juan-luis-arias** [gbrits/ionic-calendar#13]
How I can install this calendar on Ionic 4?

Thanks!

**Comment by jdanielrodriguez** [comment]
i have the same problem, please any solution?

`[ng] ERROR in ./node_modules/ionic3-calendar-en/src/calendar/calendar.module.ts
[ng] Module build failed: Error: /Applications/MAMP/htdocs/torneos/appTorneos/node_modules/ionic3-calendar-en/src/calendar/calendar.module.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
[ng] The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
[ng]     at AngularCompilerPlugin.getCompiledFile (/Applications/MAMP/htdocs/torneos/appTorneos/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:740:23)
[ng]     at plugin.done.then (/Applications/MAMP/htdocs/torneos/appTorneos/node_modules/@ngtools/webpack/src/loader.js:41:31)
[ng]     at <anonymous>
[ng]     at process._tickCallback (internal/process/next_tick.js:188:7)`

**Comment by juan-luis-arias** [comment]
Hola como estas?

Me fijo hoy que puede ser el error y te aviso mañana.

Saludos!

**Comment by jdanielrodriguez** [comment]
MUCHAS GRACIIAAASS!!!! Crei que tendria que usar otra librería jaja muchas gracias


El 28/08/2018, a las 13:59, juanariaswayne <notifications@github.com<mailto:notifications@github.com>> escribió:

Hola como estas?

Me fijo hoy que puede ser el error y te aviso mañana.

Saludos!

**Comment by jyacot** [comment]
Pareciera que sólo es necesario agregar la librería "moment" y actualizar "ionic-angular" por "@ionic/angular"

**Comment by renzdvd** [comment]
> i have the same problem, please any solution?
> 
> `[ng] ERROR in ./node_modules/ionic3-calendar-en/src/calendar/calendar.module.ts [ng] Module build failed: Error: /Applications/MAMP/htdocs/torneos/appTorneos/node_modules/ionic3-calendar-en/src/calendar/calendar.module.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property. [ng] The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv). [ng] at AngularCompilerPlugin.getCompiledFile (/Applications/MAMP/htdocs/torneos/appTorneos/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:740:23) [ng] at plugin.done.then (/Applications/MAMP/htdocs/torneos/appTorneos/node_modules/@ngtools/webpack/src/loader.js:41:31) [ng] at <anonymous> [ng] at process._tickCallback (internal/process/next_tick.js:188:7)`

Did you manage to solve this issue?

**Comment by gbrits** [comment]
As @jyacot stated - the only necessities would be to add the `moment` library and to update all instances of `ionic-angular` to `@ionic/angular` - best of luck with it, until someone makes adequate changes that I can merge to this repo - I simply no longer have the time to keep this updated myself.

**Comment by IamSurendraThota** [comment]
after installing the momentjs also still same issue,, any update ??
