### ISSUE TITLE
Issue when the first  selecting day is not in the current month

### ISSUE THREAD

**Issue by ShreefReda** [gbrits/ionic-calendar#14]
<img width="1440" alt="screen shot 2018-09-30 at 4 26 40 pm" src="https://user-images.githubusercontent.com/17913315/46258623-205be300-c4ce-11e8-9295-270014e93d85.png">

When i open the calendar and select a day at the first time in another month it shown the error in the screenshot , any help ?

**Comment by scademir** [comment]
Hi SheefReda,

In the node_module/ionic3-calendar-en/src/calendar/calendar.ts search for the line:
this.dateArray[this.lastSelect].isSelect = false;

And replace it for
        if (this.lastSelect <= this.dateArray.length) {
            this.dateArray[this.lastSelect].isSelect = false;
        }

This line is trying to clean the last day selected, but sometimes the number of daySelected is greater than the Array.length.
