### ISSUE TITLE
Cannot find module moment

### ISSUE THREAD

**Issue by veronesecoms** [gbrits/ionic-calendar#15]
I recently installed this package, when i try to serve, i receive:

Cannot find module 'moment'

**import * as moment from moment**

How can i fix this?

**Comment by SdSalaat** [comment]
i installed moment.js externally. But it should be installed while installing Plugin.

This solved my issue

**npm install --save moment**

**Comment by nitishxp** [comment]
@SdSalaat 
I am not able use this plugin plz help
