### ISSUE TITLE
How can i change the template?

### ISSUE THREAD

**Issue by veronesecoms** [gbrits/ionic-calendar#16]
I'm trying to change the template in calendar.html, but i don't see my changes. There's one special that i have to do?
the button > is not responsible and i need to do changes

**Comment by szemel** [comment]
@veronesecoms You need to edit html code in  src/calendar/calendar.ts file.

**Comment by harshadduasane** [comment]
@szemel i'm also trying to do some changes in template but its not worked.
@veronesecoms have you  got solution on this?

**Comment by szemel** [comment]
@harshadduasane After edit ts file you have to compile ts file into js file...

**Comment by bobolat** [comment]
@szemel what do you mean by this "After edit ts file you have to compile ts file into js file"? sorry i didn't understand, i'm trying to edit the template and try both edit at calendar.html and calendar.ts but not working

**Comment by gbrits** [comment]
Hi @bobolat, thanks for using the calendar, even though this is a bit outdated now - as @szemel stated once you have made the changes you can compile those changes using `tsc` - have a look at installing typescript and how to compile changes using typescript -- https://www.dyclassroom.com/howto-mac/how-to-install-typescript-on-mac-using-node-npm
