### ISSUE TITLE
ion-calender is not a known element

### ISSUE THREAD

**Issue by nitishxp** [gbrits/ionic-calendar#17]
core.js:1449 ERROR Error: Uncaught (in promise): Error: Template parse errors:
'ion-calendar' is not a known element:
1. If 'ion-calendar' is an Angular component, then verify that it is part of this module.
2. If 'ion-calendar' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
<ion-content padding class="Summary">

  [ERROR ->]<ion-calendar #calendar></ion-calendar>

  <div id="container" style="display: block;"></div>

My ionic info

Ionic:

   ionic (Ionic CLI)  : 4.3.1 (D:\ProgramData\npm\node_modules\ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.1.11

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : not available
   Cordova Plugins       : not available

System:

   NodeJS : v8.11.3 (D:\Program Files\nodejs\node.exe)
   npm    : 5.6.0
   OS     : Windows 10

**Comment by nitishxp** [comment]
@gbrits @yammusic @szemel 
Can u help me?

**Comment by szemel** [comment]
@nitishxp Did you add CalendarModule in app.module.ts file?

**Comment by nitishxp** [comment]
@szemel  Yes i have added

**Comment by szemel** [comment]
@nitishxp 
First let see if things below works :).
1. git clone https://github.com/szemel/calendarTest
2. go to folder
3. npm install 
4. ionic serve
5. Fresh project should run. On first page you sould see calendar. Did it works?

**Comment by szemel** [comment]
![image](https://user-images.githubusercontent.com/16744790/48662479-cebde680-ea82-11e8-9785-5eb2e391ffa4.png)
It should look like this.

**Comment by nitishxp** [comment]
Yeah @szemel calendarTest ran successfully..

**Comment by nitishxp** [comment]
@szemel is there a chance that a package might be conflicting or the way i am importing things might be the issue? or because i am lazyloading the page

**Comment by nitishxp** [comment]
@szemel calendar is working fine when I am not lazyloading the page. Issue occurs when i am trying lazy loading 

Thanks

**Comment by nitishxp** [comment]
@szemel how to dynamically update events data? calander is not showing updated events data when I am changing month then it's showing..any idea how to fix it?

**Comment by szemel** [comment]
@nitishxp
`this.currentEvents = [
  {
    year: 2017,
    month: 11,
    date: 25
  },
  {
    year: 2017,
    month: 11,
    date: 26
  }
];

<ion-calendar #calendar [events]="currentEvents" >

`
When you change currentEvents array ex. append new element, calendar should be automatically refresh data on calendar.

**Comment by nitishxp** [comment]
@szemel nothing is happening when my appending new elements when i am changing the months
and coming back to the original one then i am finding my changes

**Comment by szemel** [comment]
@nitishxp It's solution for your problem. https://github.com/szemel/calendarTest/commit/59ba5b62eb306ebc3eb2f0a37cac0b81c85b83e9

**Comment by nitishxp** [comment]
@szemel 
ng:///CalendarModule/Calendar.ngfactory.js:9 ERROR TypeError: lang.localeData is not a function
    at weekdayName.transform (vendor.js:195201)
    at checkAndUpdatePureExpressionInline (vendor.js:13601)
    at checkAndUpdateNodeInline (vendor.js:14314)
    at checkAndUpdateNode (vendor.js:14253)
    at debugCheckAndUpdateNode (vendor.js:15146)
    at debugCheckRenderNodeFn (vendor.js:15125)
    at Object.eval [as updateRenderer] (ng:///CalendarModule/Calendar.ngfactory.js:12)
    at Object.debugUpdateRenderer [as updateRenderer] (vendor.js:15110)
    at checkAndUpdateView (vendor.js:14224)
    at callViewAction (vendor.js:14570)
View_Calendar_1 @ ng:///CalendarModule/Calendar.ngfactory.js:9

new error is coming

**Comment by szemel** [comment]
@nitishxp Did your html look like this? <ion-calendar #calendar lang="en" [events]="currentEvents"></ion-calendar> . add lang="en"

**Comment by nitishxp** [comment]
![image](https://user-images.githubusercontent.com/25002490/48665072-6d236980-eace-11e8-8721-eb317f41ea52.png)

Why css is not taking effect?

**Comment by nitishxp** [comment]
@szemel Thanks it;s working now :)
👍 👍 👍 👍 👍 👍
