### ISSUE TITLE
Support for Ionic 4

### ISSUE THREAD

**Issue by KamayaniT** [gbrits/ionic-calendar#20]
Hi, 
The plugin is not supported by latest Ionic version/Angular version . 
![error](https://user-images.githubusercontent.com/10322679/51986820-1c18f400-24c7-11e9-83da-c7cfc8daa57b.PNG)

Please add support for this.

**Comment by gbrits** [comment]
Duplicate of https://github.com/gbrits/ionic-calendar/issues/13
