### ISSUE TITLE
get event data on click

### ISSUE THREAD

**Issue by ahmadkhalaf1** [gbrits/ionic-calendar#4]
hello how can i get Event Data on click?
i want to add note , location , title  , to the event and fetch them on each date with event click ?

i only get this object on date select 
date:25
hasEvent:true
isSelect:true
isThisMonth:true
isToday:false
month:0
year:2018
----------------------
even i added them to my object
this.currentEvents = [
			{
				year: 2018,
				month: 0,
				date: 25,
				note:'aaasss',
				title:'sweq',
				location:'qqqqwww'
			},
			{
				year: 2018,
				month: 0,
				date: 26,
				note:'qqzzccc',
				title:'jjjk',
				location:'oooo'
			}
		];

**Comment by gbrits** [comment]
You would need to reduce your own object to perform this lookup. This is not an issue with the repository, just a use case question.

An example usage:
```
onDaySelect(event: any) {
      let eventMonth = event.month + 1;
      let eventYear = event.year;
      if(eventMonth==13) { eventMonth = 1; eventYear++; }
      let dateObj = this.week.convertDateToDateObj( eventYear+'-'+eventMonth+'-'+event.date );
      if(this.week.checkIfPast(dateObj)){
        this.selectDay(dateObj);
        let x = document.getElementsByClassName("today");
        if(x.length > 0){
          x[0].classList.remove("today");
        }
      } else {
        event.preventDefault;
        event.stopPropagation;
      }
    }
```

Best of luck with your particular implementation.
