### ISSUE TITLE
I'm not sure how to use add events to the calendar....

### ISSUE THREAD

**Issue by minihiro384** [gbrits/ionic-calendar#7]
Hi, I'm very new to coding itself.

I have successfully installed this ionic2-calendar into my ionic folder. It is running smoothly. Theres one more step I'd like to move on to.

Where for events it says that this is the right format:

this.currentEvents = [
{
year: 2017,
month: 11,
date: 25
},
{
year: 2017,
month: 11,
date: 26
}
];

But it is not showing on my calendar and as for theses lines of code:

<ion-calendar #calendar [events]="currentEvents" (onDaySelect)="onDaySelect($event)" (onMonthSelect)="onMonthSelect($event)">
Error: _co.onDaySelect() is not a function.

<ion-calendar #calendar (onDaySelect)="onDaySelect($event)">

it gives out error.

Could you possibly upload more detailed information about the implantation?

**Comment by gbrits** [comment]
Hi @minihiro384 sorry for the late response - you would have to create a method of `onDaySelect` that would then be used for your project - it's complaining that you don't have a function that exists for it, where you are using it. Also make sure you are viewing November 2017 if you are putting those dates in - inspect element to see if the event blips are present for styling.

    onDaySelect(event: any) {
        console.log(event);
    }

**Comment by RaymondRowland** [comment]
gbrits, i was reading your comment about onDaySelect. I would like to know where do i have to write:
onDaySelect(event: any) {
    console.log(event);
}
And where do i have to write:
this.currentEvents = [
  {
    year: 2017,
    month: 11,
    date: 25
  },
  {
    year: 2017,
    month: 11,
    date: 26
  }
];
