### ISSUE TITLE
Error on production mode!!

### ISSUE THREAD

**Issue by jeanassy** [gbrits/ionic-calendar#8]
The plugin works when i run the app in dev mode, but when i try to run it in prod mode, i get the following error:

> 
> Error: ./src/pages/events/list.component.ngfactory.js
> Module not found: Error: Can't resolve '../../../node_modules/ionic3-calendar-en/src/calendar/calendar.ngfactory' in '/var/www/applicationLions/src/pages/events'
> resolve '../../../node_modules/ionic3-calendar-en/src/calendar/calendar.ngfactory' in '/var/www/applicationLions/src/pages/events'
>   using description file: /var/www/applicationLions/package.json (relative path: ./src/pages/events)
>     Field 'browser' doesn't contain a valid alias configuration
>   after using description file: /var/www/applicationLions/package.json (relative path: ./src/pages/events)
>     using description file: /var/www/applicationLions/node_modules/ionic3-calendar-en/package.json (relative path: ./src/calendar/calendar.ngfactory)
>       no extension
>         Field 'browser' doesn't contain a valid alias configuration
>         /var/www/applicationLions/node_modules/ionic3-calendar-en/src/calendar/calendar.ngfactory doesn't exist
>       .ts
>         Field 'browser' doesn't contain a valid alias configuration
>         /var/www/applicationLions/node_modules/ionic3-calendar-en/src/calendar/calendar.ngfactory.ts doesn't exist
>       .js
>         Field 'browser' doesn't contain a valid alias configuration
>         /var/www/applicationLions/node_modules/ionic3-calendar-en/src/calendar/calendar.ngfactory.js doesn't exist
>       .json
>         Field 'browser' doesn't contain a valid alias configuration
>         /var/www/applicationLions/node_modules/ionic3-calendar-en/src/calendar/calendar.ngfactory.json doesn't exist
>       as directory
>         /var/www/applicationLions/node_modules/ionic3-calendar-en/src/calendar/calendar.ngfactory doesn't exist
> [/var/www/applicationLions/node_modules/ionic3-calendar-en/src/calendar/calendar.ngfactory]
> [/var/www/applicationLions/node_modules/ionic3-calendar-en/src/calendar/calendar.ngfactory.ts]
> [/var/www/applicationLions/node_modules/ionic3-calendar-en/src/calendar/calendar.ngfactory.js]
> [/var/www/applicationLions/node_modules/ionic3-calendar-en/src/calendar/calendar.ngfactory.json]
> [/var/www/applicationLions/node_modules/ionic3-calendar-en/src/calendar/calendar.ngfactory]
>  @ ./src/pages/events/list.component.ngfactory.js 35:0-96
>  @ ./src/app/app.module.ngfactory.js
>  @ ./src/app/main.ts
>     at new BuildError (/var/www/applicationLions/node_modules/@ionic/app-scripts/dist/util/errors.js:16:28)
>     at callback (/var/www/applicationLions/node_modules/@ionic/app-scripts/dist/webpack.js:121:28)
>     at emitRecords.err (/var/www/applicationLions/node_modules/webpack/lib/Compiler.js:269:13)
>     at Compiler.emitRecords (/var/www/applicationLions/node_modules/webpack/lib/Compiler.js:375:38)
>     at emitAssets.err (/var/www/applicationLions/node_modules/webpack/lib/Compiler.js:262:10)
>     at applyPluginsAsyncSeries1.err (/var/www/applicationLions/node_modules/webpack/lib/Compiler.js:368:12)
>     at next (/var/www/applicationLions/node_modules/tapable/lib/Tapable.js:218:11)
>     at Compiler.compiler.plugin (/var/www/applicationLions/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:99:4)
>     at Compiler.applyPluginsAsyncSeries1 (/var/www/applicationLions/node_modules/tapable/lib/Tapable.js:222:13)
>     at Compiler.afterEmit (/var/www/applicationLions/node_modules/webpack/lib/Compiler.js:365:9)

**Comment by gbrits** [comment]
I'm looking into this now @jeanassy - did you have any luck with it?

**Comment by jeanassy** [comment]
@gbrits not yet the error occurs only when i run ionic cordova build --prod

**Comment by gbrits** [comment]
The only fix I've found so far is to copy the component (src/calendar) calendar folder directly into a components folder in your app, then reference the module from within your app, rather than via the node modules relative path, for now. Obviously this is a manual fix and not desired, but if time is factor, this may be your best for now until I can figure it out.

**Comment by jeanassy** [comment]
I'll try that, but meanwhile please find a stable fix for it. thank you.

**Comment by brunocarazato** [comment]
Same problem here. Any change?

**Comment by Blanketsniffer** [comment]
@gbrits is there a drawback of your solution other than manual effort?

**Comment by lluisnieto** [comment]
Interested. Any update?

**Comment by iodev** [comment]
Did I do something wrong or am I missing something? Or, is this module not compatible with 'browser' platform?

Calendar shows up fine in development build, but when I do a production build, I get this:

```
npm run build:prod

> HTS@0.0.1 build:prod /mnt/g/GitHub/HTSApp
> ionic-app-scripts build --prod --target cordova --platform browser

[11:01:43]  ionic-app-scripts 3.1.11
[11:01:43]  build prod started ...
[11:01:43]  clean started ...
[11:01:43]  clean finished in 4 ms
[11:01:43]  copy started ...
[11:01:43]  deeplinks started ...
[11:01:43]  deeplinks finished in 337 ms
[11:01:43]  ngc started ...
[11:01:53]  ngc finished in 10.01 s
[11:01:53]  preprocess started ...
[11:01:53]  preprocess finished in 1 ms
[11:01:53]  webpack started ...
[11:01:54]  copy finished in 11.62 s
[11:02:40]  ionic-app-script task: "build"
[11:02:40]  Error: ./src/pages/patient-details/patient-details.ngfactory.js Module not found: Error: Can't resolve
            '../../../node_modules/ionic3-calendar-en/src/calendar/calendar.ngfactory' in
            '/mnt/g/GitHub/HTSApp/src/pages/patient-details' resolve
            '../../../node_modules/ionic3-calendar-en/src/calendar/calendar.ngfactory' in
            '/mnt/g/GitHub/HTSApp/src/pages/patient-details' using description file: /mnt/g/GitHub/HTSApp/package.json
            (relative path: ./src/pages/patient-details) Field 'browser' doesn't contain a valid alias configuration
            after using description file: /mnt/g/GitHub/HTSApp/package.json (relative path: ./src/pages/patient-details)
            using description file: /mnt/g/GitHub/HTSApp/node_modules/ionic3-calendar-en/package.json (relative path:
            ./src/calendar/calendar.ngfactory) no extension Field 'browser' doesn't contain a valid alias configuration
            /mnt/g/GitHub/HTSApp/node_modules/ionic3-calendar-en/src/calendar/calendar.ngfactory doesn't exist .ts Field
            'browser' doesn't contain a valid alias configuration
            /mnt/g/GitHub/HTSApp/node_modules/ionic3-calendar-en/src/calendar/calendar.ngfactory.ts doesn't exist .js
            Field 'browser' doesn't contain a valid alias configuration
            /mnt/g/GitHub/HTSApp/node_modules/ionic3-calendar-en/src/calendar/calendar.ngfactory.js doesn't exist .json
            Field 'browser' doesn't contain a valid alias configuration
            /mnt/g/GitHub/HTSApp/node_modules/ionic3-calendar-en/src/calendar/calendar.ngfactory.json doesn't exist as
            directory /mnt/g/GitHub/HTSApp/node_modules/ionic3-calendar-en/src/calendar/calendar.ngfactory doesn't exist
            [/mnt/g/GitHub/HTSApp/node_modules/ionic3-calendar-en/src/calendar/calendar.ngfactory]
            [/mnt/g/GitHub/HTSApp/node_modules/ionic3-calendar-en/src/calendar/calendar.ngfactory.ts]
            [/mnt/g/GitHub/HTSApp/node_modules/ionic3-calendar-en/src/calendar/calendar.ngfactory.js]
            [/mnt/g/GitHub/HTSApp/node_modules/ionic3-calendar-en/src/calendar/calendar.ngfactory.json]
            [/mnt/g/GitHub/HTSApp/node_modules/ionic3-calendar-en/src/calendar/calendar.ngfactory] @
            ./src/pages/patient-details/patient-details.ngfactory.js 29:0-96 @
            ./src/pages/patient-details/patient-details.module.ngfactory.js @ ./src lazy @
            ./node_modules/ionic-angular/util/ng-module-loader.js @ ./src/app/app.module.ngfactory.js @
            ./src/app/main.ts
```

**Comment by garoqui** [comment]
The module has this issue Cannot find module 'moment'.
[app-scripts]        L1:  import { Component, Input, Output, EventEmitter } from '@angular/core';
[app-scripts]        L2:  import * as moment from 'moment';
[app-scripts]        L3:  import * as _ from "lodash";

**Comment by wahyuam** [comment]
build --release is working for me

**Comment by Deformator** [comment]
@garoqui So what we should do to prevent it? Did you fix it?

**Comment by Deformator** [comment]
Finally I resolve this problem. Yes it's because of import dependencies as @garoqui mentioned.
And cause of the problem is **better** auto import from "typescript": "~2.6.2".
Downgrading the typescript version to "typescript": "~2.4.2" in your package.json will resolve the problem with --prod.

**Comment by gbrits** [comment]
Please see @Deformator's solution for this issue.

> Finally I resolve this problem. Yes it's because of import dependencies as @garoqui mentioned.
> And cause of the problem is **better** auto import from "typescript": "~2.6.2".
> Downgrading the typescript version to "typescript": "~2.4.2" in your package.json will resolve the problem with --prod.

**Comment by sumitrvi** [comment]
@Deformator Thank u you saved my day.But i"m confusing why this kind of issue occurring?

**Comment by kapilSoni101** [comment]
@Deformator : thanks a lot sir finally its working for me.
